# Add path variables
#export PATH="$HOME/.rvm/bin:$PATH" # Add RVM to PATH for scripting
#export PATH="$HOME/.bin:$PATH"
export PATH="/usr/local/bin:$PATH"
alias octave-cli="/usr/local/octave/3.8.0/bin/octave-3.8.0"

# From ut
source ~/.antigen.zsh
antigen use oh-my-zsh

antigen bundle git
antigen bundle zsh-users/zsh-syntax-highlighting

antigen apply
antigen theme Soliah
